/**
 * Writes the Shiki language and theme names the main thread needs, without the
 * grammar and theme imports that come attached to `shiki/langs` and
 * `shiki/themes`. Re-run after upgrading Shiki; `CodeUtils.test.ts` fails when
 * the two drift apart.
 */

import { writeFile } from "node:fs/promises";
import { bundledLanguagesInfo } from "shiki/langs";
import { bundledThemesInfo } from "shiki/themes";

const languages = bundledLanguagesInfo.map((info) => info.id);
const languageAliases = Object.fromEntries(
	bundledLanguagesInfo.flatMap((info) =>
		(info.aliases ?? []).map((alias) => [alias, info.id]),
	),
);
const themes = bundledThemesInfo.map((info) => info.id);

const source = `// Generated by \`scripts/write-code-metadata.ts\` — do not edit.

import type { BundledLanguage, BundledTheme } from "shiki";

export const CODE_LANGUAGES: BundledLanguage[] = ${JSON.stringify(languages)};

export const CODE_LANGUAGE_ALIASES: Record<string, BundledLanguage> = ${JSON.stringify(languageAliases)};

export const CODE_THEMES: BundledTheme[] = ${JSON.stringify(themes)};
`;

await writeFile(
	new URL("../src/core/utils/CodeMetadata.ts", import.meta.url),
	source,
);
