[package]
name = "tiny-chat"
version = "0.0.0"
authors = ["Ryan Garber <ryanmichaelgarber@gmail.com>"]
edition = "2024"

[lib]
name = "tinychat_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
default = []
afm = ["dep:swift-rs"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.22"
futures-util = "0.3.32"
regex = "1"
reqwest = "0.13.3"
serde = "1.0.228"
serde_json = "1.0.150"
shellexpand = "3.1.2"
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2.5.3"
tauri-plugin-os = "2"
tauri-plugin-process = "2"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["default", "full"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.build-dependencies]
swift-rs = { version = "1", features = ["build"], optional = true }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
swift-rs = { version = "1", optional = true }
