const THEMES = ["dark", "light"] as const;

const CODE_THEMES_BY_THEME = {
	dark: [
		"andromeeda",
		"aurora-x",
		"ayu-dark",
		"ayu-mirage",
		"catppuccin-frappe",
		"catppuccin-macchiato",
		"catppuccin-mocha",
		"dark-plus",
		"dracula",
		"dracula-soft",
		"everforest-dark",
		"github-dark",
		"github-dark-default",
		"github-dark-dimmed",
		"github-dark-high-contrast",
		"gruvbox-dark-hard",
		"gruvbox-dark-medium",
		"gruvbox-dark-soft",
		"horizon",
		"houston",
		"kanagawa-dragon",
		"kanagawa-wave",
		"laserwave",
		"material-theme",
		"material-theme-darker",
		"material-theme-lighter",
		"material-theme-ocean",
		"material-theme-palenight",
		"min-dark",
		"monokai",
		"night-owl",
		"nord",
		"one-dark-pro",
		"plastic",
		"poimandres",
		"red",
		"rose-pine",
		"rose-pine-moon",
		"slack-dark",
		"solarized-dark",
		"synthwave-84",
		"tokyo-night",
		"vesper",
		"vitesse-black",
		"vitesse-dark",
	],
	light: [
		"ayu-light",
		"catppuccin-latte",
		"everforest-light",
		"github-light",
		"github-light-default",
		"github-light-high-contrast",
		"gruvbox-light-hard",
		"gruvbox-light-medium",
		"gruvbox-light-soft",
		"horizon-bright",
		"kanagawa-lotus",
		"light-plus",
		"min-light",
		"night-owl-light",
		"one-light",
		"rose-pine-dawn",
		"slack-ochin",
		"snazzy-light",
		"solarized-light",
		"vitesse-light",
	],
} as const;

export const ThemeUtils = {
	themes: THEMES,
	codeThemes: Object.values(CODE_THEMES_BY_THEME).flat(),
	codeThemesByTheme: CODE_THEMES_BY_THEME,
} as const;
