import { FileUtils } from "./FileUtils.ts";
import { PathUtils } from "./PathUtils.ts";

/** Why a file was left out of a search. */
export type FileSkipReason =
	| "excluded"
	| "large"
	| "binary"
	| "minified"
	| "generated"
	| "unreadable";

/** Bytes past which a file is never searched (it is machine output, not source). */
const MAX_FILE_BYTES = 512_000;

/** A line this long only occurs in bundled, minified, or single-line data files. */
const MAX_LINE_CHARS = 2_000;

/** Average line length past which a file reads as data rather than source. */
const MAX_AVERAGE_LINE_CHARS = 400;

/** How much of a file is inspected for binary bytes and generation markers. */
const SAMPLE_CHARS = 8_000;

const GENERATED_MARKERS =
	/@generated|generated by|do not edit|auto-?generated|this file is automatically/i;

export const FileExcludeUtils = {
	maxFileBytes: MAX_FILE_BYTES,

	names: new Set([
		"__macosx",
		".ds_store",
		"thumbs.db",
		".git",
		".hg",
		".svn",
		".gitignore",
		".gitattributes",
		".gitmodules",
		"node_modules",
		"bower_components",
		"jspm_packages",
		"vendor",
		"pnpm-lock.yaml",
		"package-lock.json",
		"yarn.lock",
		"bun.lock",
		"bun.lockb",
		"deno.lock",
		"cargo.lock",
		"gemfile.lock",
		"poetry.lock",
		"uv.lock",
		"composer.lock",
		"mix.lock",
		"flake.lock",
		"go.sum",
		".pnp.cjs",
		".pnp.loader.mjs",
		".yarn",
		".pnpm-store",
		"dist",
		"build",
		"out",
		"target",
		"bin",
		"obj",
		".next",
		".nuxt",
		".svelte-kit",
		".output",
		".astro",
		".angular",
		".expo",
		".docusaurus",
		".vercel",
		".netlify",
		".serverless",
		".turbo",
		".parcel-cache",
		".cache",
		"coverage",
		".nyc_output",
		"__pycache__",
		".pytest_cache",
		".mypy_cache",
		".ruff_cache",
		".tox",
		".venv",
		"venv",
		".gradle",
		".terraform",
		"pods",
		"deriveddata",
	]),

	extensions: new Set([
		"class",
		"o",
		"so",
		"dll",
		"exe",
		"dylib",
		"pyc",
		"pyo",
		"jar",
		"war",
		"a",
		"lib",
		"map",
		"lock",
		"wasm",
		"bin",
		"dat",
		"db",
		"sqlite",
		"sqlite3",
		"pack",
		"idx",
		"png",
		"jpg",
		"jpeg",
		"gif",
		"ico",
		"webp",
		"svg",
		"bmp",
		"tiff",
		"psd",
		"mp3",
		"mp4",
		"wav",
		"mov",
		"avi",
		"mkv",
		"webm",
		"flac",
		"ogg",
		"ttf",
		"woff",
		"woff2",
		"eot",
		"otf",
		"icns",
		"zip",
		"tar",
		"gz",
		"bz2",
		"xz",
		"zst",
		"rar",
		"7z",
		"iso",
		"dmg",
		"deb",
		"rpm",
		"apk",
		"aab",
		"ipa",
		"nupkg",
		"whl",
		"pdf",
		"docx",
		"xlsx",
		"pptx",
	]),

	/**
	 * Whether a path is worth walking into or reading at all. Applies to names
	 * only — content checks happen once a file has been read.
	 */
	include: (path: string) => {
		const parts = PathUtils.split(path).map((part) => part.toLowerCase());
		if (parts.some((part) => FileExcludeUtils.names.has(part))) return false;

		const name = parts.at(-1) ?? "";
		if (/\.min\.(js|css|mjs|cjs)$/.test(name)) return false;
		if (/\.generated\.[a-z]+$/.test(name)) return false;

		const extension = name.includes(".") ? name.split(".").at(-1) : undefined;
		return !extension || !FileExcludeUtils.extensions.has(extension);
	},

	/**
	 * Binary content is detected from the bytes themselves rather than the
	 * extension, so unknown or extension-less formats are still caught.
	 */
	isBinary: ({ data }: { data: Uint8Array }): boolean => {
		const length = Math.min(data.length, SAMPLE_CHARS);
		let control = 0;
		for (let index = 0; index < length; index++) {
			const byte = data[index];
			if (byte === 0) return true;
			// Tab, newline, carriage return and form feed are ordinary in text.
			if (byte < 9 || (byte > 13 && byte < 32)) control++;
		}
		return length > 0 && control / length > 0.1;
	},

	/**
	 * Bundles, minified assets and single-line data files carry very little
	 * signal per character, and one match in them can swamp a whole result set.
	 */
	isMinified: ({ text }: { text: string }): boolean => {
		if (text.length < 5_000) return false;

		let longest = 0;
		let lines = 0;
		let start = 0;
		while (start <= text.length) {
			const index = text.indexOf("\n", start);
			const end = index === -1 ? text.length : index;
			longest = Math.max(longest, end - start);
			lines++;
			if (index === -1) break;
			start = index + 1;
		}

		if (longest > MAX_LINE_CHARS) return true;
		return text.length / Math.max(1, lines) > MAX_AVERAGE_LINE_CHARS;
	},

	/** Machine-written files announce themselves in their first lines. */
	isGenerated: ({ text }: { text: string }): boolean =>
		GENERATED_MARKERS.test(text.slice(0, SAMPLE_CHARS)),

	/**
	 * The single check a search runs against a file it has read. Returns the
	 * reason to skip it, or null when the file should be searched.
	 */
	getSkipReason: ({
		path,
		data,
		maxBytes = MAX_FILE_BYTES,
	}: {
		path: string;
		data: Uint8Array;
		maxBytes?: number;
	}):
		| { reason: FileSkipReason; text?: undefined }
		| { reason: null; text: string } => {
		if (!FileExcludeUtils.include(path)) return { reason: "excluded" };
		if (data.length > maxBytes) return { reason: "large" };
		if (FileExcludeUtils.isBinary({ data })) return { reason: "binary" };

		const text = FileUtils.getTextFromBytes({ data });
		if (text === null) return { reason: "unreadable" };
		if (FileExcludeUtils.isMinified({ text })) return { reason: "minified" };
		if (FileExcludeUtils.isGenerated({ text })) return { reason: "generated" };

		return { reason: null, text };
	},
};
