import { FileUtils } from "./FileUtils.ts";
import { PathUtils } from "./PathUtils.ts";

/**
 * FileExcludeUtils — the one place that decides what a file operation is
 * allowed to see.
 *
 * Every path is sorted into at most one {@link FileCategory}, and each
 * {@link FileScope} declares which categories it turns away. That split exists
 * because "should this be excluded" has no answer on its own: a PNG is noise to
 * a text search and the entire point of an upload of screenshots.
 *
 *   `all`     — nothing is withheld. Reading a file or listing one directory
 *               answers a question about a path the caller already named, so
 *               there is nothing to protect them from.
 *   `listing` — only what is certainly not authored: version control internals,
 *               installed dependency trees, tool caches and OS debris. Media,
 *               archives, logs and build output all survive, because a caller
 *               asking which files exist is entitled to know.
 *   `search`  — everything above plus every format that cannot usefully be read
 *               as text, everything a machine wrote, and credentials.
 *
 * `.gitignore` belongs to `search` alone, for the same reason: it records what
 * is not tracked, not what is not there.
 *
 * PDFs, Word documents and spreadsheets are deliberately uncategorised. They
 * are stored as they arrived and unpacked when something reads one
 * ({@link FileExtractionService}), so a `.pdf` is prose that a search can match
 * on and excluding it by name would hide the very document that was attached.
 * Formats with no converter — `.doc`, `.pptx`, `.pages` — need no rule either:
 * the binary-bytes check below turns them away on content, which is also the
 * right answer for the ones nobody has thought of.
 */

/** What a path is, when it is something other than authored source. */
export type FileCategory =
	| "junk"
	| "vcs"
	| "dependency"
	| "cache"
	| "build"
	| "lockfile"
	| "minified"
	| "generated"
	| "media"
	| "binary"
	| "archive"
	| "data"
	| "secret";

/** Why a file was left out of a search: its kind, or something about its bytes. */
export type FileSkipReason = FileCategory | "large" | "unreadable";

/** How much a given operation is willing to withhold. */
export type FileScope = "all" | "listing" | "search";

/** Bytes past which a file is never searched (it is machine output, not source). */
const MAX_FILE_BYTES = 512_000;

/** A line this long only occurs in bundled, minified, or single-line data files. */
const MAX_LINE_CHARS = 2_000;

/** Average line length past which a file reads as data rather than source. */
const MAX_AVERAGE_LINE_CHARS = 400;

/** How much of a file is inspected for binary bytes and generation markers. */
const SAMPLE_CHARS = 8_000;

const GENERATED_MARKERS =
	/@generated|generated by|do not edit|auto-?generated|this file is automatically/i;

/**
 * Categories whose names are far too ordinary to act on for a file: `bin`,
 * `build`, `out` and `deps` are all plausible things to call a script or a
 * note, and only ever mean what they say as a directory.
 */
const DIRECTORY_ONLY = new Set<FileCategory>(["dependency", "build"]);

/**
 * Names that would otherwise be caught, and are worth keeping: a committed
 * environment template documents configuration rather than holding any.
 */
const KEEP = new Set([
	".env.example",
	".env.sample",
	".env.template",
	".env.defaults",
	".env.dist",
	"env.example",
]);

const getLookup = (groups: [FileCategory, string[]][]) =>
	new Map<string, FileCategory>(
		groups.flatMap(([category, names]) =>
			names.map((name) => [name, category] as const),
		),
	);

/** Matched against any path segment, lower-cased, on every OS. */
const NAMES = getLookup([
	[
		// Debris written by Finder, Explorer, archivers and editors.
		"junk",
		[
			"__macosx",
			".ds_store",
			".ds_store?",
			".appledouble",
			".applesingle",
			".appledb",
			".appledesktop",
			".localized",
			".lsoverride",
			".spotlight-v100",
			".documentrevisions-v100",
			".temporaryitems",
			".trashes",
			".fseventsd",
			".volumeicon.icns",
			".com.apple.timemachine.donotpresent",
			"network trash folder",
			"temporary items",
			"thumbs.db",
			"ehthumbs.db",
			"ehthumbs_vista.db",
			"desktop.ini",
			"$recycle.bin",
			"recycler",
			"system volume information",
			"pagefile.sys",
			"hiberfil.sys",
			"swapfile.sys",
			".trash",
			".trash-1000",
			".directory",
			".nfs",
		],
	],
	[
		// The object stores themselves. `.gitignore` and friends are authored
		// files and are deliberately absent: they are small, and reading one
		// answers real questions about a project.
		"vcs",
		[".git", ".hg", ".svn", ".bzr", "_darcs", "cvs", ".jj", ".pijul"],
	],
	[
		// Trees that a package manager wrote and can write again. Only names
		// that mean this and nothing else — `vendor` and `deps` are common
		// enough as ordinary folders that they are treated as build output
		// instead, and so survive a listing.
		"dependency",
		[
			"node_modules",
			"bower_components",
			"jspm_packages",
			".pnpm",
			".pnpm-store",
			".yarn",
			".npm",
			".nuget",
			".m2",
			".ivy2",
			".gradle",
			".cargo",
			".cabal",
			".stack-work",
			".bundle",
			"site-packages",
			"__pypackages__",
			".eggs",
			".venv",
			"venv",
			".virtualenvs",
			".conda",
			".pyenv",
			"pods",
			"carthage",
			".swiftpm",
			".dart_tool",
			".pub-cache",
			".terraform",
			".cpan",
			".cpanm",
		],
	],
	[
		// Recomputable by definition, and usually enormous.
		"cache",
		[
			".cache",
			".caches",
			"__pycache__",
			".pytest_cache",
			".mypy_cache",
			".ruff_cache",
			".pytype",
			".nox",
			".tox",
			".ipynb_checkpoints",
			".sass-cache",
			".parcel-cache",
			".turbo",
			".nx",
			".rush",
			".rpt2_cache",
			".vite",
			".rollup.cache",
			".webpack",
			".esbuild",
			".ccache",
			".sccache",
			".fingerprint",
			".eslintcache",
			".stylelintcache",
			".prettiercache",
			".metals",
			".bloop",
			".ammonite",
			"deriveddata",
			".gradle-cache",
		],
	],
	[
		// Written by a build, a test run or a bundler. Excluded from search
		// because the source that produced it is already there; kept in a
		// listing because an upload of a built site is a real thing to send.
		"build",
		[
			"dist",
			"dist-newstyle",
			"build",
			"builds",
			"out",
			"output",
			"target",
			"bin",
			"obj",
			"objs",
			"release",
			"debug",
			"_build",
			".build",
			"cmakefiles",
			"vendor",
			"deps",
			"generated",
			"__generated__",
			".next",
			".nuxt",
			".svelte-kit",
			".output",
			".astro",
			".angular",
			".expo",
			".docusaurus",
			".vercel",
			".netlify",
			".serverless",
			".wrangler",
			".vitepress",
			".vuepress",
			"_site",
			"storybook-static",
			"coverage",
			".nyc_output",
			"htmlcov",
			"playwright-report",
			"test-results",
			"allure-results",
			"xcuserdata",
			// Unity, Unreal and Godot all keep regenerable trees beside sources.
			// `logs` is deliberately absent: a directory of logs is a normal
			// thing to send someone precisely so that it can be searched.
			"library",
			"temp",
			"usersettings",
			"binaries",
			"intermediate",
			"saved",
			"deriveddatacache",
			".godot",
			".import",
		],
	],
	[
		// A resolved dependency graph: enormous, and it says nothing the
		// manifest beside it does not.
		"lockfile",
		[
			"pnpm-lock.yaml",
			"package-lock.json",
			"npm-shrinkwrap.json",
			"shrinkwrap.yaml",
			"yarn.lock",
			"bun.lock",
			"bun.lockb",
			"deno.lock",
			"cargo.lock",
			"gemfile.lock",
			"poetry.lock",
			"pipfile.lock",
			"pdm.lock",
			"uv.lock",
			"composer.lock",
			"mix.lock",
			"flake.lock",
			"go.sum",
			"gopkg.lock",
			"podfile.lock",
			"package.resolved",
			"packages.lock.json",
			"packages-lock.json",
			"pubspec.lock",
			"gradle.lockfile",
			"renv.lock",
			"conan.lock",
			"cabal.project.freeze",
			".terraform.lock.hcl",
			".pnp.cjs",
			".pnp.loader.mjs",
		],
	],
	[
		// Credentials. Withheld from search so that a broad query cannot sweep
		// a key into the conversation; `read_file` will still open one when it
		// is asked for by name.
		"secret",
		[
			// The `.env` family is spelled out as well as matched by pattern,
			// so that the SQL translation below can see it too.
			".env",
			".env.local",
			".env.development",
			".env.production",
			".env.staging",
			".env.test",
			".ssh",
			".gnupg",
			".aws",
			".netrc",
			"_netrc",
			".pgpass",
			".my.cnf",
			".htpasswd",
			"credentials",
			"id_rsa",
			"id_dsa",
			"id_ecdsa",
			"id_ed25519",
			"secring.gpg",
		],
	],
]);

/** Matched against the extension of a file, lower-cased. */
const EXTENSIONS = getLookup([
	[
		// Compiled output, bytecode, native modules and model weights.
		"binary",
		[
			"class",
			"o",
			"obj",
			"so",
			"dll",
			"exe",
			"dylib",
			"lib",
			"a",
			"pdb",
			"ilk",
			"node",
			"pyc",
			"pyo",
			"pyd",
			"jar",
			"war",
			"ear",
			"wasm",
			"bc",
			"rlib",
			"rmeta",
			"beam",
			"elc",
			"hi",
			"cmi",
			"cmo",
			"cmx",
			"nupkg",
			"whl",
			"egg",
			"gem",
			"crx",
			"xpi",
			"pt",
			"pth",
			"ckpt",
			"safetensors",
			"onnx",
			"tflite",
			"mlmodel",
			"gguf",
			"ggml",
			"bin",
			"epub",
			"mobi",
			"azw3",
			"chm",
		],
	],
	[
		// Images, audio, video, fonts, 3D and design documents.
		"media",
		[
			"png",
			"jpg",
			"jpeg",
			"jpe",
			"jfif",
			"gif",
			"bmp",
			"ico",
			"cur",
			"webp",
			"avif",
			"heic",
			"heif",
			"jxl",
			"tif",
			"tiff",
			"tga",
			"exr",
			"hdr",
			"psd",
			"psb",
			"ai",
			"eps",
			"sketch",
			"fig",
			"xd",
			"afdesign",
			"afphoto",
			"svgz",
			"raw",
			"cr2",
			"cr3",
			"nef",
			"arw",
			"dng",
			"orf",
			"raf",
			"icns",
			"mp3",
			"m4a",
			"aac",
			"wav",
			"aiff",
			"aif",
			"flac",
			"ogg",
			"oga",
			"opus",
			"wma",
			"mid",
			"midi",
			"mp4",
			"m4v",
			"mov",
			"avi",
			"mkv",
			"webm",
			"wmv",
			"flv",
			"3gp",
			"mpg",
			"mpeg",
			"ttf",
			"ttc",
			"otf",
			"woff",
			"woff2",
			"eot",
			"pfb",
			"fbx",
			"blend",
			"gltf",
			"glb",
			"stl",
			"3ds",
			"dae",
			"usdz",
			"ply",
			"unitypackage",
		],
	],
	[
		"archive",
		[
			"zip",
			"tar",
			"tgz",
			"gz",
			"bz2",
			"tbz2",
			"xz",
			"txz",
			"zst",
			"lz4",
			"lzma",
			"rar",
			"7z",
			"cab",
			"iso",
			"img",
			"dmg",
			"pkg",
			"msi",
			"deb",
			"rpm",
			"apk",
			"aab",
			"ipa",
			"appimage",
			"snap",
			"flatpak",
			"vhd",
			"vmdk",
			"pack",
			"idx",
		],
	],
	[
		// Stores and datasets: opaque, or far past the point where reading one
		// line at a time tells you anything.
		"data",
		[
			"db",
			"sqlite",
			"sqlite3",
			"db-shm",
			"db-wal",
			"mdb",
			"accdb",
			"dbf",
			"frm",
			"myd",
			"myi",
			"ibd",
			"rdb",
			"dat",
			"parquet",
			"avro",
			"orc",
			"feather",
			"arrow",
			"npy",
			"npz",
			"pkl",
			"pickle",
			"joblib",
			"h5",
			"hdf5",
			"mat",
		],
	],
	[
		// Private keys, certificate bundles and password stores. `key` is
		// ambiguous with Keynote, and both belong on this side of the line.
		"secret",
		[
			"pem",
			"key",
			"p12",
			"pfx",
			"keystore",
			"jks",
			"ppk",
			"asc",
			"gpg",
			"kdbx",
		],
	],
	[
		// Editor swap files, partial downloads and merge leftovers.
		"junk",
		[
			"swp",
			"swo",
			"swn",
			"swm",
			"tmp",
			"temp",
			"bak",
			"orig",
			"rej",
			"crdownload",
			"part",
		],
	],
	["lockfile", ["lock"]],
	[
		// Source maps, and the scene and asset files a game engine serialises
		// on the developer's behalf.
		"generated",
		[
			"map",
			"tsbuildinfo",
			"meta",
			"prefab",
			"unity",
			"asset",
			"controller",
			"mixer",
			"anim",
			"physicmaterial",
		],
	],
]);

/** Matched against a whole path segment when a plain name cannot say enough. */
const PATTERNS: {
	category: FileCategory;
	pattern: RegExp;
	fileOnly?: boolean;
}[] = [
	// Office and LibreOffice lock files, Emacs locks and autosaves, editor
	// backups, and the stubs NFS leaves behind for open deleted files.
	{ category: "junk", pattern: /^~\$/, fileOnly: true },
	{ category: "junk", pattern: /^\.~lock\./, fileOnly: true },
	{ category: "junk", pattern: /^\.#/, fileOnly: true },
	{ category: "junk", pattern: /^#.*#$/, fileOnly: true },
	{ category: "junk", pattern: /~$/, fileOnly: true },
	{ category: "junk", pattern: /^\._/, fileOnly: true },
	{ category: "junk", pattern: /^\.nfs[0-9a-f]{6,}$/, fileOnly: true },
	{ category: "build", pattern: /^cmake-build-/ },
	{ category: "build", pattern: /\.(dsym|xcarchive|framework)$/ },
	{ category: "dependency", pattern: /\.egg-info$/ },
	{ category: "minified", pattern: /\.min\.(js|mjs|cjs|css)$/, fileOnly: true },
	{
		category: "minified",
		pattern: /\.(bundle|chunk)\.(js|mjs|cjs|css)$/,
		fileOnly: true,
	},
	{ category: "generated", pattern: /\.generated\.[a-z0-9]+$/, fileOnly: true },
	// Protobuf, gRPC and code generators across the languages that use them.
	{
		category: "generated",
		pattern: /[._]pb2?(_grpc)?\.(py|go|rb|js|ts)$/,
		fileOnly: true,
	},
	{ category: "generated", pattern: /\.(g|freezed|gr)\.dart$/, fileOnly: true },
	{ category: "generated", pattern: /\.designer\.(cs|vb)$/, fileOnly: true },
	{ category: "secret", pattern: /^\.env($|\.)/, fileOnly: true },
	{ category: "secret", pattern: /^id_[a-z0-9]+(\.pub)?$/, fileOnly: true },
];

/** Categories each scope refuses, in order of how much they withhold. */
const SCOPES: Record<FileScope, ReadonlySet<FileCategory>> = {
	all: new Set(),
	listing: new Set(["junk", "vcs", "dependency", "cache"]),
	search: new Set([
		"junk",
		"vcs",
		"dependency",
		"cache",
		"build",
		"lockfile",
		"minified",
		"generated",
		"media",
		"binary",
		"archive",
		"data",
		"secret",
	]),
};

/** Short phrases for reporting a skip back to the model. */
const REASONS: Record<FileSkipReason, string> = {
	junk: "operating system",
	vcs: "version control",
	dependency: "dependency",
	cache: "cache",
	build: "build output",
	lockfile: "lockfile",
	minified: "minified",
	generated: "generated",
	media: "image, audio, video or font",
	binary: "compiled",
	archive: "archive",
	data: "database or dataset",
	secret: "credential",
	large: "oversized",
	unreadable: "unreadable",
};

export const FileExcludeUtils = {
	maxFileBytes: MAX_FILE_BYTES,
	reasons: REASONS,

	/** Every category a scope turns away, for callers that need the raw set. */
	getScope: (scope: FileScope): ReadonlySet<FileCategory> => SCOPES[scope],

	/**
	 * The literal names and extensions behind a set of categories, for the one
	 * caller that cannot run this code over each path: a SQL `WHERE` clause.
	 * Pattern rules have no equivalent there and are left out, so a translation
	 * of these is always the loose half of the filter.
	 *
	 * `directoryOnly` selects the names that only count as a directory, so a
	 * translation can hold them to the same rule this file does.
	 */
	getNames: ({
		categories,
		directoryOnly,
	}: {
		categories: ReadonlySet<FileCategory>;
		directoryOnly?: boolean;
	}): string[] =>
		[...NAMES]
			.filter(
				([, category]) =>
					categories.has(category) &&
					(directoryOnly === undefined ||
						DIRECTORY_ONLY.has(category) === directoryOnly),
			)
			.map(([name]) => name),

	getExtensions: ({
		categories,
	}: {
		categories: ReadonlySet<FileCategory>;
	}): string[] =>
		[...EXTENSIONS]
			.filter(([, category]) => categories.has(category))
			.map(([extension]) => extension),

	/**
	 * What a path is, regardless of who is asking. Answers for the first
	 * segment that is recognisable, so a source file inside `node_modules` is a
	 * dependency rather than source.
	 *
	 * `root` is the directory the caller started from, and only the part of the
	 * path below it is judged. Without it, checking out a project into
	 * `~/Library/work` or `~/dist` would exclude every file in it.
	 */
	getCategory: ({
		path,
		root,
		isDirectory = false,
	}: {
		path: string;
		root?: string;
		isDirectory?: boolean;
	}): FileCategory | null => {
		const parts = PathUtils.split(
			root ? PathUtils.relative({ base: root, path }) : path,
		);
		const last = parts.length - 1;

		for (let index = 0; index <= last; index++) {
			const segment = parts[index].toLowerCase();
			if (KEEP.has(segment)) continue;

			// Anything with a segment after it is a directory, whatever the
			// caller knows about the path as a whole.
			const directory = index < last || isDirectory;

			const named = NAMES.get(segment);
			if (named && (directory || !DIRECTORY_ONLY.has(named))) return named;

			for (const rule of PATTERNS) {
				if (rule.fileOnly && directory) continue;
				if (!directory && DIRECTORY_ONLY.has(rule.category)) continue;
				if (rule.pattern.test(segment)) return rule.category;
			}

			if (directory) continue;

			const dot = segment.lastIndexOf(".");
			const extension = dot > 0 ? segment.slice(dot + 1) : undefined;
			const typed = extension ? EXTENSIONS.get(extension) : undefined;
			if (typed) return typed;
		}

		return null;
	},

	/**
	 * The category that keeps a path out of this scope, or null when the scope
	 * is happy to see it. Callers that only need a yes or no use
	 * {@link include}; the category is there to be reported.
	 */
	getExcluded: ({
		path,
		root,
		scope = "search",
		isDirectory = false,
	}: {
		path: string;
		root?: string;
		scope?: FileScope;
		isDirectory?: boolean;
	}): FileCategory | null => {
		if (scope === "all") return null;
		const category = FileExcludeUtils.getCategory({ path, root, isDirectory });
		return category && SCOPES[scope].has(category) ? category : null;
	},

	/**
	 * Whether a path is worth walking into or reading at all. Applies to names
	 * only — content checks happen once a file has been read.
	 */
	include: ({
		path,
		root,
		scope = "search",
		isDirectory = false,
	}: {
		path: string;
		root?: string;
		scope?: FileScope;
		isDirectory?: boolean;
	}): boolean =>
		FileExcludeUtils.getExcluded({ path, root, scope, isDirectory }) === null,

	/**
	 * Binary content is detected from the bytes themselves rather than the
	 * extension, so unknown or extension-less formats are still caught.
	 */
	isBinary: ({ data }: { data: Uint8Array }): boolean => {
		const length = Math.min(data.length, SAMPLE_CHARS);
		let control = 0;
		for (let index = 0; index < length; index++) {
			const byte = data[index];
			if (byte === 0) return true;
			// Tab, newline, carriage return and form feed are ordinary in text.
			if (byte < 9 || (byte > 13 && byte < 32)) control++;
		}
		return length > 0 && control / length > 0.1;
	},

	/**
	 * Bundles, minified assets and single-line data files carry very little
	 * signal per character, and one match in them can swamp a whole result set.
	 */
	isMinified: ({ text }: { text: string }): boolean => {
		if (text.length < 5_000) return false;

		let longest = 0;
		let lines = 0;
		let start = 0;
		while (start <= text.length) {
			const index = text.indexOf("\n", start);
			const end = index === -1 ? text.length : index;
			longest = Math.max(longest, end - start);
			lines++;
			if (index === -1) break;
			start = index + 1;
		}

		if (longest > MAX_LINE_CHARS) return true;
		return text.length / Math.max(1, lines) > MAX_AVERAGE_LINE_CHARS;
	},

	/** Machine-written files announce themselves in their first lines. */
	isGenerated: ({ text }: { text: string }): boolean =>
		GENERATED_MARKERS.test(text.slice(0, SAMPLE_CHARS)),

	/**
	 * The single check a search runs against a file it has read. Returns the
	 * reason to skip it, or null when the file should be searched.
	 */
	getSkipReason: ({
		path,
		root,
		data,
		scope = "search",
		maxBytes = MAX_FILE_BYTES,
	}: {
		path: string;
		root?: string;
		data: Uint8Array;
		scope?: FileScope;
		maxBytes?: number;
	}):
		| { reason: FileSkipReason; text?: undefined }
		| { reason: null; text: string } => {
		const excluded = FileExcludeUtils.getExcluded({ path, root, scope });
		if (excluded) return { reason: excluded };
		if (data.length > maxBytes) return { reason: "large" };
		if (FileExcludeUtils.isBinary({ data })) return { reason: "binary" };

		const text = FileUtils.getTextFromBytes({ data });
		if (text === null) return { reason: "unreadable" };
		if (FileExcludeUtils.isMinified({ text })) return { reason: "minified" };
		if (FileExcludeUtils.isGenerated({ text })) return { reason: "generated" };

		return { reason: null, text };
	},
} as const;
