import { describe, expect, it } from "vitest";
import type { ShellCapability } from "../../capability/types/capability.ts";
import { FileSearchService } from "./FileSearchService.ts";

export const createShell = (
	initial: Record<string, string | Uint8Array>,
): ShellCapability => {
	const files = new Map(Object.entries(initial));
	return {
		readFile: async ({ path }) => {
			const content = files.get(path);
			if (content === undefined) throw new Error(`Missing file: ${path}`);
			return {
				path,
				data:
					typeof content === "string"
						? new TextEncoder().encode(content)
						: content,
			};
		},
		readDir: async ({ path }) => {
			const prefix = path.endsWith("/") ? path : `${path}/`;
			const entries = new Map<string, boolean>();
			for (const filePath of files.keys()) {
				if (!filePath.startsWith(prefix)) continue;
				const remainder = filePath.slice(prefix.length);
				const [name, ...rest] = remainder.split("/");
				entries.set(`${prefix}${name}`, rest.length > 0);
			}
			return [...entries].map(([entryPath, is_dir]) => ({
				path: entryPath,
				is_dir,
			}));
		},
		writeFile: async ({ path, content }) => {
			files.set(path, content);
			return { path, success: true };
		},
		exec: async () => ({ stdout: "", stderr: "" }),
	};
};

describe("FileSearchService", () => {
	describe("walk", () => {
		it("skips dependency and build directories", async () => {
			const shell = createShell({
				"/project/src/app.ts": "app",
				"/project/node_modules/dep/index.js": "dep",
				"/project/dist/app.js": "built",
			});

			const { entries } = await FileSearchService.walk({
				shell,
				path: "/project",
			});

			expect(entries.map((entry) => entry.path)).toEqual([
				"/project/src/app.ts",
			]);
		});

		// Git itself cannot re-include a file whose parent directory is ignored,
		// and neither does the walk: `generated/` is never descended into.
		it("honours .gitignore", async () => {
			const shell = createShell({
				"/project/.gitignore": "*.log\ngenerated/\n!generated/keep.ts\n",
				"/project/app.ts": "app",
				"/project/debug.log": "noise",
				"/project/generated/schema.ts": "generated",
				"/project/generated/keep.ts": "kept",
			});

			const { entries } = await FileSearchService.walk({
				shell,
				path: "/project",
			});

			expect(entries.map((entry) => entry.path)).toEqual(["/project/app.ts"]);
		});

		it("reports truncation instead of walking forever", async () => {
			const files: Record<string, string> = {};
			for (let index = 0; index < 50; index++) {
				files[`/project/file-${index}.ts`] = "x";
			}

			const { entries, truncated } = await FileSearchService.walk({
				shell: createShell(files),
				path: "/project",
				maxEntries: 10,
			});

			expect(entries).toHaveLength(10);
			expect(truncated).toBe(true);
		});
	});

	describe("grep", () => {
		it("returns numbered lines and a coverage summary", async () => {
			const shell = createShell({
				"/project/a.ts": "const answer = 42;\nconst other = 1;\n",
				"/project/b.ts": "const answer = 'unknown';\n",
			});

			const report = await FileSearchService.grep({
				shell,
				path: "/project",
				query: "answer\\s*=\\s*42",
			});

			expect(report.results).toEqual([
				{ path: "/project/a.ts", snippet: "1: const answer = 42;", matches: 1 },
			]);
			expect(report.summary).toContain("1 match(es) in 1 file(s)");
		});

		it("is case-insensitive until the query says otherwise", async () => {
			const shell = createShell({ "/project/a.ts": "const Answer = 1;\n" });

			await expect(
				FileSearchService.grep({ shell, path: "/project", query: "answer" }),
			).resolves.toMatchObject({ results: [{ path: "/project/a.ts" }] });

			await expect(
				FileSearchService.grep({ shell, path: "/project", query: "ANSWER" }),
			).resolves.toMatchObject({ results: [] });
		});

		it("caps what a single file may contribute", async () => {
			const shell = createShell({
				"/project/a.ts": "match\n".repeat(1_000),
			});

			const report = await FileSearchService.grep({
				shell,
				path: "/project",
				query: "match",
			});

			expect(report.results[0].matches).toBe(1_000);
			expect(report.results[0].snippet.split("\n").length).toBeLessThanOrEqual(
				10,
			);
			expect(report.summary).toContain("1000 match(es)");
		});

		it("skips minified, generated and binary files", async () => {
			const shell = createShell({
				"/project/bundle.js": `const needle = 1;${"x".repeat(6_000)}`,
				"/project/schema.ts": `// Code generated by prisma. DO NOT EDIT.\nconst needle = 2;\n`,
				"/project/blob.txt": new Uint8Array([110, 0, 1, 2, 3]),
				"/project/real.ts": "const needle = 3;\n",
			});

			const report = await FileSearchService.grep({
				shell,
				path: "/project",
				query: "needle",
			});

			expect(report.results.map((result) => result.path)).toEqual([
				"/project/real.ts",
			]);
			expect(report.stats.skipped).toMatchObject({
				minified: 1,
				generated: 1,
				binary: 1,
			});
		});

		it("filters by an include glob", async () => {
			const shell = createShell({
				"/project/src/a.ts": "needle",
				"/project/src/a.test.ts": "needle",
			});

			const report = await FileSearchService.grep({
				shell,
				path: "/project",
				query: "needle",
				include: "**/*.test.ts",
			});

			expect(report.results.map((result) => result.path)).toEqual([
				"/project/src/a.test.ts",
			]);
		});

		it("explains an unusable regular expression", async () => {
			await expect(
				FileSearchService.grep({
					shell: createShell({ "/project/a.ts": "a" }),
					path: "/project",
					query: "(unclosed",
				}),
			).rejects.toThrow(/Invalid regular expression/);
		});

		it("matches literally when asked", async () => {
			const shell = createShell({
				"/project/a.ts": "const cost = a[0] + b;\n",
			});

			await expect(
				FileSearchService.grep({
					shell,
					path: "/project",
					query: "a[0]",
					literal: true,
				}),
			).resolves.toMatchObject({ results: [{ path: "/project/a.ts" }] });
		});
	});

	describe("search", () => {
		it("ranks the defining file above one that repeats the term", async () => {
			const shell = createShell({
				"/project/src/user-service.ts":
					"export const getUserSession = () => session;",
				"/project/src/log.ts": "user session\n".repeat(500),
			});

			const report = await FileSearchService.search({
				shell,
				path: "/project",
				query: "getUserSession",
			});

			expect(report.results[0].path).toBe("/project/src/user-service.ts");
		});

		it("keeps every result within the snippet budget", async () => {
			const files: Record<string, string> = {};
			for (let index = 0; index < 20; index++) {
				files[`/project/file-${index}.ts`] = "const user = 1;\n".repeat(2_000);
			}

			const report = await FileSearchService.search({
				shell: createShell(files),
				path: "/project",
				query: "user",
				maxResults: 10,
			});

			const total = report.results.reduce(
				(length, result) => length + result.snippet.length,
				0,
			);
			expect(report.results).toHaveLength(10);
			expect(total).toBeLessThanOrEqual(8_000);
		});

		it("finds files by path when the contents say nothing", async () => {
			const shell = createShell({
				"/project/src/checkout/index.ts": "export {};",
				"/project/src/other.ts": "export {};",
			});

			const report = await FileSearchService.search({
				shell,
				path: "/project",
				query: "checkout",
			});

			expect(report.results.map((result) => result.path)).toEqual([
				"/project/src/checkout/index.ts",
			]);
		});
	});

	describe("glob", () => {
		it("returns paths matching a pattern without reading them", async () => {
			const shell = createShell({
				"/project/src/a.ts": "a",
				"/project/src/b.tsx": "b",
				"/project/readme.md": "c",
			});

			await expect(
				FileSearchService.glob({ shell, path: "/project", pattern: "**/*.ts" }),
			).resolves.toEqual({ paths: ["/project/src/a.ts"], truncated: false });
		});
	});
});
